let projectId=null,poll=null,currentFilter='ALL';
const $=id=>document.getElementById(id);
const DURUM={PENDING:'BEKLİYOR',READY:'HAZIR',RUNNING:'ÇALIŞIYOR',DONE:'TAMAMLANDI',FAILED:'BAŞARISIZ',NEEDS_REVIEW:'İNCELEME GEREKLİ',DEFERRED:'ERTELENDİ',BLOCKED:'ENGELLENDİ',LOADED:'YÜKLENDİ',COMPLETED:'PROJE TAMAMLANDI',COMPLETED_WITH_OPEN_ITEMS:'AÇIK MADDELERLE TAMAMLANDI',FAILED_NO_PROGRESS:'İLERLEME YOK',PAUSED_HUMAN_AUTH:'İNSAN ONAYI İÇİN DURAKLATILDI'};
const FACTORY={WAITING:'BEKLİYOR',RUNNING:'ÇALIŞIYOR',COMPLETED:'TAMAMLANDI',FAILED:'BAŞARISIZ',RETRYING:'YENİDEN DENENİYOR',SKIPPED:'ATLANDI',NEEDS_REVIEW:'İNCELEME GEREKLİ',DEFERRED:'ERTELENDİ'};
const when=value=>value?new Intl.DateTimeFormat('tr-TR',{timeZone:'Europe/Istanbul',dateStyle:'short',timeStyle:'medium'}).format(new Date(value)):'—';
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const body=await response.json();if(!response.ok)throw new Error(body.reason||body.error||`HTTP ${response.status}`);return body}
function ids(state,status){return state.work_units.filter(unit=>unit.status===status).map(unit=>unit.id).join(', ')||'—'}
function resultText(unit){if(unit.last_result?.summary)return unit.last_result.summary;if(unit.qa_lead_status)return `QA Lideri: ${unit.qa_lead_status}`;if(unit.blocked_reason)return unit.blocked_reason;return '—'}
function stageName(name){return String(name||'Bilinmeyen aşama').replace(/Analyst/g,'Analist').replace(/Specialist/g,'Uzman').replace(/Planner/g,'Planlayıcı').replace(/Consistency Reviewer/g,'Tutarlılık Denetçisi').replace(/Developer/g,'Geliştirici').replace(/Deterministic QA/g,'Deterministik Kalite Kontrol').replace(/QA Lead/g,'Kalite Kontrol Lideri').replace(/Factory Inspector/g,'Fabrika Denetçisi').replace(/Factory Telemetry Publisher/g,'Fabrika Telemetri Yayıncısı')}
function activityText(node){const state=node.status||'WAITING';if(state==='COMPLETED')return 'Aşama geçerli sprint çalışmasında tamamlandı.';if(state==='RUNNING')return 'Aşama gerçek çalışma kanıtına göre çalışıyor.';if(state==='FAILED')return 'Bu aşamada kayıtlı teknik hata oluştu.';if(state==='RETRYING')return 'Aşama sınırlı yeniden deneme sürecinde.';if(state==='SKIPPED')return 'Bu yedek aşama çağrılmadı.';if(state==='NEEDS_REVIEW')return 'Bu aşama insan incelemesi gerektiriyor.';if(state==='DEFERRED')return 'Bu aşama kanıtla ertelendi.';return 'Geçerli sprintte henüz çalıştırılmadı.'}
function visible(unit){return currentFilter==='ALL'||unit.status===currentFilter}
function renderProject(state){
  projectId=state.project_id;const terminal=(state.counts.DONE||0)+(state.counts.FAILED||0)+(state.counts.NEEDS_REVIEW||0)+(state.counts.DEFERRED||0)+(state.counts.BLOCKED||0);
  $('project').textContent=`${state.project_id} — ${state.project_title}`;$('status').textContent=DURUM[state.status]||state.status;$('ust-durum').textContent=DURUM[state.status]||state.status;$('started').textContent=when(state.started_at);$('progress').textContent=`${terminal} / ${state.total}`;$('done').textContent=state.counts.DONE||0;$('fail-count').textContent=state.counts.FAILED||0;$('review-count').textContent=state.counts.NEEDS_REVIEW||0;$('health').textContent=Number.isFinite(state.project_health)?`${state.project_health} / 100`:'—';
  const current=state.work_units.find(unit=>unit.id===state.current_work_unit_id);$('current').textContent=current?`Geçerli İş Birimi: ${current.id} — ${current.title}`:'Geçerli İş Birimi: —';$('failed').textContent=ids(state,'FAILED');$('review').textContent=ids(state,'NEEDS_REVIEW');$('blocked').textContent=ids(state,'BLOCKED');$('deferred').textContent=ids(state,'DEFERRED');$('start').disabled=state.status!=='LOADED';$('pause').disabled=state.status!=='RUNNING';$('resume').disabled=state.status!=='PAUSED_HUMAN_AUTH';
  $('units').replaceChildren(...state.work_units.filter(visible).map(unit=>{const tr=document.createElement('tr');for(const [index,value] of [unit.id,unit.title,unit.priority,(unit.dependencies||[]).join(', ')||'—',DURUM[unit.status]||unit.status,resultText(unit),when(unit.updated_at)].entries()){const td=document.createElement('td');td.textContent=value;if(index===4)td.className=unit.status;tr.appendChild(td)}return tr}));
}
async function refreshProject(){if(!projectId)return;try{renderProject(await api(`/api/projects/${encodeURIComponent(projectId)}`))}catch(error){$('message').textContent=error.message}}
function renderFactory(data){$('factory-status').textContent=FACTORY[data.factory_status]||'BEKLİYOR';$('sprint-id').textContent=data.sprint_id||'Henüz gözlenmedi';$('factory-stage').textContent=stageName(data.current_stage||'—');$('factory-updated').textContent=when(data.updated_at);$('factory-score').textContent=Number.isFinite(data.inspector?.sprint_score)?`${data.inspector.sprint_score} / 100`:'—';const nodes=Array.isArray(data.nodes)?data.nodes:[];$('factory-nodes').replaceChildren(...nodes.map(node=>{const tr=document.createElement('tr');for(const value of [stageName(node.name),`${FACTORY[node.status]||node.status||'BEKLİYOR'} — ${activityText(node)}`,when(node.updated_at)]){const td=document.createElement('td');td.textContent=value;tr.appendChild(td)}return tr}));$('factory-message').textContent=`Salt okunur yerel telemetri • 5 saniyede bir yenilenir • ${nodes.length} aşama`}
async function refreshFactory(){try{renderFactory(await api('/api/factory-status'))}catch{$('factory-message').textContent='Fabrika telemetrisi şu anda kullanılamıyor.'}}
$('validate').onclick=async()=>{try{const plan=JSON.parse($('manifest').value);const result=await api('/api/projects/validate',{method:'POST',body:JSON.stringify(plan)});$('message').textContent=`PLAN GEÇERLİ — ${result.project_title}, ${result.work_unit_count} iş birimi. Doğrulama üretimi başlatmadı.`}catch(error){$('message').textContent=`Plan reddedildi: ${error.message}`}};
$('load').onclick=async()=>{try{const plan=JSON.parse($('manifest').value);const state=await api('/api/projects/prepare',{method:'POST',body:JSON.stringify(plan)});renderProject(state);$('message').textContent='Proje değişmez plan ve çalışma durumu olarak yüklendi. Üretim henüz başlamadı.';clearInterval(poll);poll=setInterval(()=>{refreshProject();refreshFactory()},3000)}catch(error){$('message').textContent=`Yükleme reddedildi: ${error.message}`}};
$('start').onclick=async()=>{try{const state=await api('/api/projects/start',{method:'POST',body:JSON.stringify({project_id:projectId})});renderProject(state);$('message').textContent='Proje üretimi açıkça başlatıldı; uygun iş birimleri sırayla ilerleyecek.'}catch(error){$('message').textContent=`Başlatma reddedildi: ${error.message}`}};
$('pause').onclick=async()=>{try{renderProject(await api(`/api/projects/${encodeURIComponent(projectId)}/pause`,{method:'POST',body:'{}'}));$('message').textContent='Duraklatma istendi; çalışan iş birimi güvenle tamamlanacak.'}catch(error){$('message').textContent=error.message}};
$('resume').onclick=async()=>{try{renderProject(await api(`/api/projects/${encodeURIComponent(projectId)}/resume`,{method:'POST',body:'{}'}));$('message').textContent='Proje sürdürüldü.'}catch(error){$('message').textContent=error.message}};
document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{currentFilter=button.dataset.filter;refreshProject()});
refreshFactory();setInterval(refreshFactory,5000);
